### PR TITLE
Have MAL compiler generate coreLang

### PR DESCRIPTION
**Pull request by simwr872**
Generated languages must provide their own version of coreLang. With this patch that is no longer needed. Already existing projects must remove their implementation of coreLang to use the latest compiler, to avoid duplication. The patch also enables the ttc-override file to be applied when an attacker attacks instead of a static file path (if no path is given, it tries the default generated path).

As an example, the code below would read and set the ttc values from `path/to/profile.ttc` when attacking.
```
Attacker att = new Attacker();
att.attack("path/to/profile.ttc");
```

### CODE REVIEW

**Comment by skatsikeas** [comment]
Hi,
I noticed that on https://github.com/pontusj101/MAL/blob/147e97b41cf3145fc881c71beb850de6225aeff6/src/main/java/core/AttackStep.java, the "assertUncompromisedFrom()" method is missing. Was it left out by accident or is there a reason for not including it?

**Comment by pdeliasson** [comment]
Sotirios,
This looks like a simple omission. As both the assertCompromisedInstantaneouslyFrom() and assertCompromisedWithEffortFrom() are available, it would not be logical to leave out assertUncompromisedFrom().

**Comment by skatsikeas** [comment]
I have added that omitted method on the /src/main/java/core/AttackStep.java but the method does not seem to propagate on the generated files inside the compiled language, it is missing from the AttackStep.java file generated. Are those methods read from somewhere else during generation?

**Comment by simwr872** [comment]
There was one method that was in vehicleLang but not coreLang that was on github. An oversight by me, a more complete set of functions is of course, better. The src/main/java/core needs to be zipped and placed by the resources (core.zip).

**Comment by skatsikeas** [comment]
Okay, I tried to do that but after I replace the core.zip file when I build I get the following weird error:

`Writing core/core/Asset.java
java.io.FileNotFoundException: /var/folders/j_/06ptl3t17mdbhwc4yqjpz_x40000gn/T/junit2604871985864662967/java/core/core/Asset.java (Not a directory)`
How are you creating the zip? I use the "zip" command line tool.

**Comment by simwr872** [comment]
Perhaps a bit unclear but the zip must contain only the core files, not any subfolder. Make sure that you're not creating a core folder in that zip. I used 7zip but I dont thini that should matter.

**Comment by skatsikeas** [comment]
Indeed that was the problem, the core directory. Okay now build works but the method is still not propagated on the language generated AttackStep.java file...

**Comment by simwr872** [comment]
Are you testing with vehicleLang? Try a mvn clean of both the compiler and vehicleLang

**Comment by skatsikeas** [comment]
Yes. I always do mvn clean install but I also tried mvn clean.

**Comment by skatsikeas** [comment]
Okay, I figured out the problem and I will patch and merge soon!

**Pull request merged**
